#!/usr/bin/with-contenv bash

if ! rustc --version &> /dev/null; then 
    echo "**** Adding rust deps to package install lists ****"
    ## Ubuntu
    if [ -f /usr/bin/apt ]; then
        echo "\
            curl \
            build-essential \
            gcc \
            make \
            runc" >> /mod-repo-packages-to-install.list
    fi
    ## Alpine
    if [ -f /sbin/apk ]; then
        echo "\
            curl \
            gcc" >> /mod-repo-packages-to-install.list
    fi
    curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh
    rustup default stable
else
    echo "**** rust already installed, skipping ****"
fi
