#!/usr/bin/with-contenv bash

if ! rustc --version &> /dev/null; then 
    echo "**** Adding rust's deps to package install lists ****"
    ## Ubuntu
    if [ -f /usr/bin/apt ]; then
        echo "\
            curl \
            build-essential \
            gcc \
            make \
            runc" >> /mod-repo-packages-to-install.list
        echo "\
            libssl-dev \
            pkg-config" >> /mod-repo-packages-to-install.list
        echo "\
            llvm-dev \
            libclang-dev \
            clang" >> /mod-repo-packages-to-install.list
    fi
else
    echo "**** rust already installed, skipping ****"
fi