#!/usr/bin/with-contenv bash

if ! rustc --version &> /dev/null; then 
    echo "Installing rustup"

    curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y
    chown -R abc:abc $HOME/.cargo $HOME/.rustup
    source "$HOME/.cargo/env"
    rustup default stable
else
    echo "**** rust already installed, skipping ****"
fi

install-extension pinage404.rust-extension-pack