#!/usr/bin/with-contenv bash

if ! rustc --version &> /dev/null; then 
    echo "Installing rustup"
    apt-get install -y curl build-essential gcc make runc
    curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y
    rustup default stable
else
    echo "**** rust already installed, skipping ****"
fi